#include <iostream>

int main() {
    std::cout << R"(
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXXKKKXXXXXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0Okkkxxdxxxdddddk0000OOKNNWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMNOxdlc:;;;;,;'..'...'',::ccllcllloooodxkOXNNXXXKKXXXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXOo:''.........  .........'......''......,;',;,'''..',',;:cldxxkOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKko:,.... ...........   ...''.......  .............    .......  ......';coxk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWN0xc;,'........      ......   ............  ...........            ....... ........,:cldOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWX0d;'........                      ..        ...         .                          ........';cdk0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNKx:.......                                   .                                   .        .........;cxKNWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKkl'.....          ...      ..                                                  ...           ..........';lxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdl;... ..            ..   ...        .                           ..             ....         ..  ..  .......,':xKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxl:,...                     .  .   ....   .                                          ..                    ........';cd0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxo:'.......          ...  ...  ...     .  ..            .             ..                           ...  ......   ...''..'',:dKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc,'';;,.....  . ..         ...   ..  ..      ..            ...           ..                              ................''..',;cdKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdc,:cc:;'.      .....        ....            ....   .. ..       ..       .                                   ...   ............''';;;:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWMWN0l';ool;'.                   ....      .    .     ....  ....              ...          ..                   ...  ....  .............''';;,cONWWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWKl;;ll:'...      ...         ....      .  ..               ...   .          ..                     ...        ....  ....  ..............''..';xKNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMNx:okd:'....  .    ..         ....    .  .  ..         ..    ..    ...        ..       ...    ..       ..        ............... ...............;x0XMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMXdckOo,....  ...             ..    ..   ...   .        .....  ...    .      ....   ..  ......    ..       ..     .  ............ .................;dONWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMKlc0O:...... ..      .       ...    .....          .  ...   ... ..    .          .. .............  ..      ...  ..     ..........  .................;kXWWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMXxokx:.....                   .       ...       ...         .....       .          .  .................. .. ....  ...    .............................;xXNWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMW0xxd:.....                  ...                 ..   .    ....  ....  . .          . ..  ................. ...........     ...........  ...............,l0WMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWW0xxc.  .              ..   ... .      ..   ...   .   ...   .........  .  .           ....................... ..........     ..........    ...............c0NWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWNOkd. ..               ..   ..  .      ..  ....   .    ............ .. .  .         .  ....................... .....  ..   . ..........     ........  .....:ONWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWXkc....                ..   .           .   ..  ....   ............... .. ..     ................................................'.......     .............':0WWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWKl..  .              ...                  ...    ....  .. ............... ..... ............................................... ..........     ..............cKWWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMXl....                .                     ..    ................. ......................................................................      ...... .. ....'oXWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMXo,...             .                .         ....  ................ ........  .........................'.....................................   ......  .......,xXWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNk:'..              .               ... ..    ..... ..............  ......................................''....................................  ..... .. .......:kNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWOl;.      ..                         ......  .................... .. .......................................'...'.................................................'dXWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMXxc....   ...                          .  ... .. .............................................................'''........'''........................................lXMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMW0dc....   ...                ..       ......  ..........................................................'''..............''''.......................................,kWWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNOd:. ..   ..              .  ..  ...  . ....  ........ .....................................'''...'''.....'..........'....''''....'..................................:KWWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMXkd;...   ..               .      ...  ..  ............  ..................................''','''...''............'..'''...'''''.''''..'.............................,oXMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMXko'...    .                .. .  ....  ............. ..............................'..............'.............''''''''''.''.';,'',,''''.'..........................'c0MMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWXOl'....   .                ..... .. ..  ..  ......... ............................''.......'...................',,''',,,''','...,;'',,,'',,'.'''.....................,cOWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWWKl.....   ..               ........ ..  ..  ....................'.................'''...'....................'''.''',,,,,,,''''..''..','',,,,'',,',,.....''..........'lkXWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWXx'.  ..  .        ...  .  .. ..............  ................................'....''.......................'.....'.''''..'...'...........',,,',;,,,...'','''.........oKNMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWNk'. ..           . ....   .............................................................'........''''........................................''.'''...'',,'''.........cXMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWO,..    ..  ....   ....   ....................''''.............................'...''''''''''..'''''''''...'''''........... .....................................'...;KMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMO,..   ...    ..    ....  .....''''..........';:c:::;;,,''.....................',,,;:::clllcccc::::::::::::::::;;;::;,''........... .... ... ....................'...:KMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMO;..     ..    .     ........':ccc::;,,,'''''',coddddddxdollccc:cllc:;,,,'',,;:looodddxxkkOOkkkOOkkkkkkkkkxxxxxxdddxxdolc:,'........ ..  ...   .... .................cXMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM0;.. .    .   ... . ........';cloooolllccccc:::ldxkkkkkOOO00OOOOOOO0OOkxdddddxk0000000000KKKKKKKKKKKKKKKKK00KK000OOOkkkkxxdol:;'.........  ........  ... ............lNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMKc.......   .  .... .......',:loddddddoooollc:::clodddxkOO0KKKKKKKKKXXXXXKKKKKXXXXXXKXXXXXXXXXXXXXXXXXXXXXXXXKK00Okxxxxddoodddool:;'...........  ..  ..  ..........'.oNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM0:. ...    ..  ..........'',:clddddddddol:;,,,,,;;:ccloddxxkkkOO0KKXXXXXXXXXXXNXNNNNXXNNNNNNNNNNNNNNNNNXXXKKK000Okxddolllcc:clooodolc:;,,'......  .       ..........'oNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM0:. ..   ....  ..........,::loddddxddlc;,''',,,,,,,,,,,;;;::cllllodk0KKKKXXXXXXNNXNNNNNNNNNNNNNXXXXKKKOkkxdoollllcc:::::::::::::cloddoollc;,......  ..    .........''dNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMKc...   .   ............,:lloddxxxdoc;,,,;::ccllcccc::::;;:::::::ccldkOO0KKKXXXXNXXNNNXXNXXXXXXKKOkxdol::;;;;;,,,,,',,;;;;;;;;;;;;:loddddooc;'.....      ..........';xWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXo...  ..   ...........,:coodxxdddoc:::cloddxkkOOOkkkOkkxxxxxddooooddkkkO000KXXXXXXXXXNNXXXXXKK00Okxolcclooooddddooddddddoooollcccccldddddddoc;.....  .  ..........,oKWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNx;..  ..  ...........';cloddddxdddolloddxkkkOO000KKXXXXXKKK00000OkOOOOO000KKKXXXXXXXXXXXXXKK000OOkkxxkkOO000000KKKKKK000OOOkkkxddooodxxdddxddl;...................c0WMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWKl...   .............,:lodddxxxxxxdddxxxkOO000OkxdddddddddddxkO0KKK000000000KKKXXXXXXXXXXKKKKKK000KK0KKKKKKKKKKKKXXXXXXKK00OOOOkkkxxxxxxxxxxdol;.........  ......;kWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNx;..    ............,coodddxxxxxxxxxkkkOOdolloooddxxkkkxxxddooolodkKK00K0KKKKKKXXXXXXXXXXKKKKKKKXXKkxdddddddddddddddodxk0K00OOOkkkkkkkxxxxxddo:'........... ...:xNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWKx:.   .............;cooddxxxxkxxxxkkkdlcclxO0KKKKKXXXXXXXNNNXX0xolclkKK00KKKKKKKKXXXXXXXKKKKKKOdlllodkO0KKXXXXXXKKOkdollloxO0OOOOkkkkkkxxxxdoc,..............,kWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWKx,.. .............;cooodxxxkkxkkxxdlclkOOO00KKKKXXXXXXNNNNNXXXXXKko:cxKK0KKKKKKKXXXXXXXKKXKxcclx0XXKKKKKXXXXXXXXXXXXKK0xoccdO0OOOOkkkkkxxxdoc,.............,oXMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWXo.  ... .....  ..,clloddooodkkkkocokOOOOOOOOkxxddooooodxk0XXXXKKKK0o;o0KKKXXXXXNNNXXKKXXx:cx0KKKKKKK0kdollllodxkO00K0000OxllxOOOOOOkkkkxxdoc'.............:0WMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWWWXl.....     ',. ...........oXNXo:dkkxkxxdol:;;:;'..,..;.'lddOKXKKKKKk::xOOxk0KkdkK0xOKOc,dKK00KKKOxdl,..'..''..;::cldkOOOOOdcoO0OOOkkkkkxdo;.............'xNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWKdllllc;'...','......''''',l0Nk:oxdddolc:;,;:oko...''.'.;OKxldOXKKK0Ox,';..,ll;.,l:..;''xKXKKKKOxoxOO:........:kxc;;,;codxkOx::kXXKl',;:c:c:'...........'dNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMW0dlloddddol:''....';:cllooooooxocxddddolcclloxkOOl'..''':kXXKkllkXK0OkOl..;lodxxxxddxc..oKKKXXKOddkkO0kl,'..';oO0OxoolcclodxkOo..lkd,...';,,od;........';dXMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMXxlc:loddxxddol'..,clooodddxxxxc;okxxxxxxkkkkkkkkkOxoolldOK00OOkxkKK0Okxc.,odk0K000kddd'.d0KKXXK0OOOOOOOOxddodkOOOOOOOOkkxxxkkxd, .;ccccc::;,;;'..',:cooddx0NMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMXdc:coodxxxxxxo,..coooodddxxxxkl'oOkkOOO000KKKKXXXKKKKKKKKKKKKXKKKKKOko;:',oxOKKKKKKklc..:d0KKXXXKKKKKKKKKKKKXXXXXXXXXKK00OOOOkk:.cxxxxxdddoc'.':lodxxkxxolo0WMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNxlcloodxkkxxxd;.'clooodddddxxko;lOkO000KKKKKXXXXXXXXXXXKXXXXXXXKKK0Ox;;;.;dO0KKXXXKKx:.':ckKKKXXXKKKKKKKKKKKXXXXXXXXXXKKK000OOk:,xOkxxxxxddo;.,oxxkkxxdlc:lOWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWOollodxxkkxxxd,.,llooodddddddxxcckOO0KKKXXXXXXXXXXXXXXXXXXXXXXXKKK0Oo,:,'lk0KKXXXXXX0o''ccdKKKXXXXXXXKKKKKXXXXXXXXXXXXKKKK00OOx:ckkkxxxxxddo:.'dkxxxdddoccdKWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMW0dolodxkkkxxxd,.,cloooddodddxxkdcd0O00KKKXXXXXXXXXXXXXXXXXXXXXKKKK0Ooc;.:xO0KXXXXXXXKOc.:ldKKXXXXXXXXXKKKXXXXXXXXXXXXXKKKK00OOo:xOkkkxxxxddoc.'dkOkxxddood0WMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWKxoloxkkkkkkxo,.,cllooddddxdxkkOdcx000KKKXXXXXXXXXXXXXXXXKXXKKKKKK0kd;':xO0KXXXXNNXXKKk;'lk0KXXXNXXXXXXXXXXXXXXXXXXXXXKKKK000dcdOkkkkkxxxddo:.;xO0OkxdoodONMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMKxooxxxddool::'.,cllooodddxxxkkOOdlx0000KKXXXXXXXXXXXXXXXXXXXXKK00Ox:'cxOO0KXXXXNNXXXKKx;,d0KKXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKxcdOOkkkkkxxxdoo:.:O0OOkxdoxONMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNkdxxdollccccc,.,:clloodddxxkkOOO0kloOKKKKKXXXXXXXXXXXXXXXXXXXKK0kl;:oxkO00KXXXXXXXXXK00x:;oOKKXXXXXXXXXXXXXXXXXXXXXXXKKKK0dcx0OOOkkkkxxddol;.,dkkkkkxxONMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMW0xxxollllllll:',:ccloooddxxkkOOOO00dlokKXKKXXXXXXXXXXXXXXXKXK0kl::lxkkkO00KXXXXXXXXXKK0Okl:cx0XXXXXXXXXXXXXXXXXXXXXXKKKKkloOKO00OOkkkxxddol;.'lodxkkkOXWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMXkxxolllooolol,';ccllooddxxkkOOOO0000xoddx0KXXXXXXXXXXXXXX0xoc:codxxxkO00KKXXXXNXXXXXK00OkdlcldOXXXXXXXXXXXXXXXXXXXXX0xookKK000OOOOkkxxdool;';loddxkOKWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWOxxollllooodd:';:cclloodxxkkOOO000000K0kdodddddxxxxxdddoollldxxxxxxxkO0KKXXXXXNNXXXXKK0OOkxdooloodk0KXNNNNNNNXXK0kddddOKXKK00000OOOkxddolc;,cddddxkOXMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMW0dxxdoccloddd:,,:cclloodxxkkOO000000KKKKKK0OkxdoooooodxkO000OkxxxxxkO0KKXXXXXNNNNNXXXK00OkkkkOOkdollooodooddddddddxOXXXXKKKK0000OOOkxddolc;;oddodxkOXMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMKdoxkxdddddol:',;:cclooddxkkkOO0000KKKXXKKKKKKKXKKKXXXXKKKKKOxdxxkOOO0KKXXNXXNNNNNNXXKK000OkO0KK00000OOkkkkkO0KXXXXXXXXXKKK0000OOOOkxxdolc;cdxdoodk0XMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNkodddxxddxxdo;,;::clloodxxkkkOO000KKKXXXXXXXXXXXXXXXXXXXXK0kdxkOO0000KKXXNNXNNNNNNXXXKK0000OOKXXXXXKXXKXXXXXXXXXXXXXXXXXKK00000OOkkxxolc:;cddodxkOKNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMKxdddddddxdddl;;::cclooddxxkkkO000KKKXXXXXXXXXXNNNNNNXNXXKOxxkOO0000000KKXXXXNNXXXXKKKKKKK0OOKXXXXXXXXXXXXXXXXXXXXXXXXXKKKK0000OOkkxdolc;;oxxkOOkkXMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWKxdxxdddddddo:,;:ccloooddxxkOOO000KKXXXXXXNNNNNNNNNNNNXK0OxxkOO000OkxkO0KKKKKXKKK0000KKKK0OOKXXXXNNNXXXXXXXXXXXXXXXXXXKKKK000OOkkxdolcc;:dkkkkxxONMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWXkdddddddddoc;;:cclloodddxkkOO000KKKXXXXXXXXXNNNNNNNXXX0OkdxkOOkd:;;cdxOOOO000kdc::lxO00OO0XXNNNNNNNXXXXXXXXXXXXXXXXKKKK000OOOkxxdolc:;cxkkkkkkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kdddddddxdc;:ccllloodddxkkOO0000KKKKXXXXXXXXNNNNNXXXKKOxddxxxddxxxxkkkkkOOOkxxxxxxkkkO0KXXNNNNNNNNNXXXXXXXXXXXXXKKKK0000OOkkxdollc::okkkkkk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdddxxxxo::ccllloooddxxkkOO0000KKKKXXXXXXXNNNNNNXXXKK0OkxdxxkO0KKKK0000KKXXK0OOkkkO0KXXNNNNNNNNXXXXXXXXXXXXXXXKKK000OOOkkkxdollc:lxkkkkkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkxxddddlcclllllooodxxkkOOO000KKKKXXXXXXXNNNNNXXXXKKKK0OOOOO00KXXXXKKKKXXXKK00000KKXXXXNNNNNNNNNNXXXXXXXXXXKKKK0000OOOkkxdoollccdkkkkOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXXXNNOlclllllooddxxkkOOO00KKKKXXXXXXXXXXXXXXXXKKKK00000000KXXXXXXKXXXXKKKKKKKKXXXXXNNNNNNNNNNNXXXXXXXXKKKKK0000OOkkxddoollloxkkk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNklcllllooddxxkkOO000KKKKKXXXXXXXXXXXXXXKKK000O00000KKXXXXXXKXXXXXKKKKKKKKXXXXNNNNNNNNNNNNXXXXXXXKKKK0000OOOkkxddoooooxkO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXdcllllooddxxkkkOO000KKKKKKKKKKKKXXXKKKK00000O00000KKKXXXXKKKKXXXXKKKKKKKKKXXXXXXNNNNNXXXXXXXXXXKKKK000OOOkkxxddoookXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0lcllloooddxxkkOO0000KKKKXXXXKKKXKKKKK000000000000KKKXXKKKKKXXXXXXKKKKKKKKKXXXXXXXXXXXXXXXXXXXKKKKK000OOOkkxxddooxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWklcllooodddxkkkOO000KKKKKKKKKKKKK000000000000000O0000KKKKKKKK000KKKKKKKKKKKXXXKXXXXXXXXXXXXXKKKKK0000OOOkkxxddodKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxcllloooddxxkkkOOO00KKKKKKKKKKK00000000000OOkkxxdxxxxxkkkxxxxxxxkkO0KXXKKXXKKKKKKKKKKXXXXXKKKKK0000OOkkkxxddooOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdcllooodddxxxkkOOO000KKKKKKK00000OOOOOOOkxdollllllloooooooooollllodkO0KKKKKKKKKKKKKKKKKKKKKKK0000OOOkkkxxddokNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKocllooodddxxxkOOO0000KKKKKKK00OkxddddoolcccccclllooooooooooollcclllloxkOOOO00KKKKKKKKKKKKKK0000OOOkkkxxddoxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKolllloodddxxkkkOO0000KKKK000Okxdlcc::clloddxxkOOOOOOOOOOOOOkkkxxxdolcclloxO00KKKKKKKKKKK00000OOOkkkxxddoxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0olllloooddxxxkkOOO00000000000OOkxxddddxxxkkkOO000000000000000OOOOOkkkkkkOO000KKKKKKKKK00000OOOkkkxxddoxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOllllloooddxxxkkOOO0000000000000OOkkxxxxxkkkkOOOO0000000000OOOO000000000000000KKKKKK000000OOOkkkxxddoxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0llllllloooddxxxkkOOO0000000000000OkkkxxxxxxxxxxxxxxxxxxkkkkkOOO000000KKKKKK00KKKK000000OOOkkkxxdddokXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKocclllllloooddxxkkOOOOO000000000000OOOOkkxxxxxxxxxxxxxxxxkkOO000KKKKKKKKKKKK0KKK00000OOOOkkxxdddodONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx:cccclllllooddxxkkkOOOO00000000KKKKKK0000000000000000O0000KKKKKKKKKKKKKKKKKKKK0000OOOOkkkxdddood0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkccccccccllllooddxxkkOOOOO00000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKKKKKKKKKKKK00000OOOkkxxddooooxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0lcllcc::cccclloodxxkOOOOOOO000000000KKKKKKKKKXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKK00000OOkkxxddoooollxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKoclllcc::::ccclloddxkOOOOOOOO0000000KKKKKXXXXXXXXXXXXXXNNNXXXXXXXKKKKKKKKKKK0000OOkkxxdooolllolkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdclllllc::::::ccloodxkOOOO000000000KKKKKXXXXXXXXXXXXXXXNNXXXXXXXXKKKKKKKKKKK000OOkxxdoollllloolOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxclllllllc::::::ccloodxkOOO000000000KKKKKKXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKK000OOkxdoollclloooolOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkclllooolllc::::::cclodxkkOO00000000000KKKKKKKKKKKKKKKXXXXXXXXXXXXXKKKKKKK00OOkxdoolcccloodooolOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOccllooooollccc::::ccclodxkkOOO0000000000000KKK00000KKKKKKKKKKKKKKKKKKKK00OOkxdoollcclooddddoooOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlcloooooooolllccc:::ccllodxxkOOOOOOO0000000000000000000KKKKKKKKKKKK0000OOkxdoollccloodddddddoox0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdlllooooooooooollcccccccclloddxxkkOOOOOOOOOOOOOOOOOOOO000000000000000OOOkxdolllllllodddxxxdddol;..;okKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxc'..cllooooooooooooollllccccccclloddxxxxxxkkOOOOOOOOOOOOOOOOOOO00OOOOOkkkxddollllloodddxxxxxxxddoo;.   .'cONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0l'.   .clloooooodddddddooollllllccccllloooooodddxxxxxxxxxxxkkkkkkkkkkkkxxddoollllooodddxxxxxxxxxxddooc.    ...cONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c...   .clclooooddddddddddddoooooollllllllllllllooooooooooooooooodddddoooooooooooodddxxxxxxxkkkkxxxddoldl.     ...lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'..    .oxlcloooddddddddddddddddooooooooooollllllllllllllllllllllllllooooooddddddxxxxxxkkkkkkkkkkkkxxddld0o.    ....;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO;...     ;kklcoooodddxxxxxxxxxxxddddddddddddddddddddoooolllllllloooodddxxxxxxxxxxxxxkkkkkkkOOOOOOOOkkxxddoxKKc    .....'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c. .      .l0OolooodddxxxxxxxxxxxxxxdddddddddxxxxxkkkkkkkkkkkkkkkkkOOOOOOOOOOkkkkkkkkkkOOOOOOOOOOOOOOkkkxxddOXXO,  ........:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl..         'x00xlooddddxxxkkkkkkkkkkxxxxddxxxxxxkkkkOOOO0000000000000000000OOOOOOOOOOOOOOOOOO00000OOOOkkkxxdkXNXKx. .... .....cONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0o;. ..        .:k0KKxlodxxxkkkkkkkkkkkkkkkxxxxxxxxxkkOOOOO000000KKKKKKKKK0000000OOOOOOOOOOOO00000000000OOOOOkkxxKWNXK0c. ...........:xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWXko;...            .lO00XXkodxxkkkkOOOOOOOOOOOkkkkxxxkkkkkkOOOO00000KKKKKKKKKK0000000OOOOOOOOO0000000000000000OOOOkkKNNNXXKo. .......  ....,lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWWXkl,..  .         ... .lO00KXNOddkkkOOOOOOOOOOOOOOOkkkkkkkkkkkkOOOO00000KKKKKKK00000000000000O0000000000000000000000O0XWWNNNXKo....... .. .......'cxKWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWKd,.....  .         ... .lO0KKXNNKxdxkkOOOO000000OOOOOOkkkkkOOOOOOOOOOOO0000000000000000000000000000000000K00000000000KNWWNNNXXKo....... .. .. .......':xXMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWWKo'....              ......:O0KKKXNNNOdxkOOOO000000000OOOOOOOOOOOOOOOOO00OOO000000000000000000000000000KKKKKKKKKKK0K0O0XWWWWNNNXXXl........................,oKWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWKl'... . .            ...... 'kKKKXXXNNWXOxkOOO00000000000OOOOOOOOOOO00000000000000000000000000000000KKKKKKKKKKKKKKKKOOKWWWWWNWWNXN0;..........................,oKWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXd'......               ........dKKXXXXXNNWWXOxxOOO0000000000OOOOOO0000000000000000000KKKKKKKK00000KKKKKKKKKKKKKKKKKKOOKNWWWWWWWWWNNNx.................... ........'oKMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMW0c....               ............c0KXXXXNNNNWWWX0kkkO0000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKOO0NWMMMWWWWWWNNNKl...............................,kWMMMMMMMMMMMMMM
MMMMMMMMMMMMMN00k;......             .............,kKXXNNNNNNNWWWWN0kkOO000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OO0NWMMMMWWWWWWWWWNk,................................'dNMMMMMMMMMMMMM
MMMMMMMMMMWKdcod,....  .           ................oKXNNNNNNNNNWWWWWNKOkkO0000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OOOKNWMMWMMMWWWWWWWWWXo...................................dX0OXWMMMMMMMM
MMMMMMMWKxc..ox,.......         . .................c0XXNNNNWNNNWWWWWWWWNKOkOO000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OO0XWWMMMMMMWWWWWWWWWWW0;................. ..................dOc,cdOXWMMMM
MMMMWXkl'..,xx;..........      ....................:OXXNNNWWWWWNWWWWWWWWWWX0OkkO0000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OOOKNWMMMMMMMMMMWWWWWWWWWNx,.................. ..........  ......dKo...':okKN
KOxo:'.. .:Ox,...........  ........................;xKXNNWWWWWWWWWWWWWWWWWWWWX0OkkOOOO00000KKKKKKKKKKKKKKKKKKKKKKKKKKK0OkkO0XWMMMMMMMMMMMMMMWWWWWWWNkc'.....................  ............. .xKd. ....':
....... .lOd'......................................'l0XNNNWWWWWWWWWWWWWWWMWWMMWNX0kkkkOOO00000KKKKKKKKKKKKKKKKKKKK000kxkOKNWMMMMMMMMMMMMMMMMMWWWWWW0d:......................  ...............'xKo.    ..
..     .c0x'........................................:xXNNNWWWWWWWWWWWWWWWWWMMMMMMWNX0kxxkOOO0000000KKKK0000K00000Okxxk0NWWWMMMMMMMMMMMMMMMMMMMWWWWXkl;........................................'kKo. .  .
       .dXd.........................................,oOXNNNWWWWWWWWWWWWWWWWMMMMMMMWMMWXOkxxkOOOO0000000000OOOOkkddxOXWMMMMMMMMMMMMMMMMMMMMWMMMMWWN0xl,.........................................;K0'     
       .cKKd;.......................... ............'lx0XNNWWWWWWWWWWWWWWWWMMMMMMMMMMMMWNKOkxxkkOOOOOOOOOOkkxdodOKWMMMMMMMMMMMMMMMMMMMMMWWMMMMWWWXkxc.........................................,dXO'     
        .:OXKkl,.......................  ............cxOXNWWWWWWWWWWWWWWWWWMMMMMMMMMMWMMMMWNKOkxxkkOOOkkkxdoox0NWMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWMN0kd,......................................,cxKNO;      
          .ckKNXOdc'.......................  ........;xOKNWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMWNKOkxxxdddoodkKWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOkc...................................;lx0XNNkc.       
.           .:kKNNNKo'...............................'d00NWWWWWWWWWWWWWWWWMMWMMMMMMMMMMMMMMMMMMWWN0kxxollkXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOd'...............................,cdOXWWWNOc.      .. 

    )" << std::endl;

    return 0;
}